---
# Docker Configuration

- name: ensure docker systemd directory exist
  file:
    path: '/etc/systemd/system/docker.service.d'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: configure Docker http_proxy
  template:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      owner: root
      group: root
      mode: 0644
  with_items:
      - { src: '50-http-proxy.conf.j2', dest: '/etc/systemd/system/docker.service.d/50-http-proxy.conf' }
  when: "http_proxy is defined and http_proxy != ''"


- name: configure Docker systemd options
  template:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      owner: root
      group: root
      mode: 0644
  with_items:
      - { src: '40-flannel.conf.j2', dest: '/etc/systemd/system/docker.service.d/40-flannel.conf' }
  notify: restart docker

- meta: flush_handlers

- name: ensure Docker is started
  systemd:
    name: 'docker'
    state: started
    enabled: yes
    daemon_reload: yes
