- name: ensure etcd is started
  systemd:
    name: etcd2
    state: started
    daemon_reload: yes

- name: wait for etcd port to be open
  wait_for:
    host: 127.0.0.1
    port: 2379
    delay: 5
    connect_timeout: 2
    timeout: 300

- name: debug
  debug:
    msg: "http://{{groups['k8s-masters'][0]}}:2379/v2/keys/coreos.com/network/config"


- name: get Pod network IP range through etcd
  run_once: true
  uri:
    url: "http://{{groups['k8s-masters'][0]}}:2379/v2/keys/coreos.com/network/config"
    method: GET
    return_content: yes
  register: pod_network_info
  when: "k8s_kublet_network_plugin == ''"


- name: configure Pod network IP range through etcd
  run_once: true
  uri:
    url: "http://{{groups['k8s-masters'][0]}}:2379/v2/keys/coreos.com/network/config"
    method: PUT
    body: "value={\"Network\":\"{{k8s_pod_network}}\",\"Backend\":{\"Type\":\"vxlan\"}}"
  when: k8s_kublet_network_plugin == '' and pod_network_info.content.find(k8s_pod_network) == -1
  notify: restart flanneld

- name: get etcd cluster info
  run_once: true
  command: 'etcdctl cluster-health'
  register: etcd_status
  changed_when: false

- name: ensure etcd cluster is healthy
  run_once: true
  assert:
    that:
      - "'cluster is healthy' in etcd_status.stdout"
