---

# Better method but SSL is not yet supported on kubernetes module in Ansible v2.2
#- name: create k8s DNS service and replication controller
#  kubernetes:
#    api_endpoint: "{{ groups['k8s-workers'] | map('extract', hostvars, ['priv_ip']) | list | random }}"
#    inline_data: "{{item}}"
#    state: present
#  with_items:
#    - "{{k8s_dns_service}}"
#    - "{{k8s_dns_replication_controller}}"

- name: generate k8s DNS service and replication controller files
  template:
    src: "{{item.src}}"
    dest: "/tmp/{{item.dest}}"
    mode: 0644
  with_items:
    - { src: "k8s_dns_service.yaml.j2", dest: 'kube-dns-svc.yaml' }
    - { src: "k8s_dns_replication_controller.yaml.j2", dest: 'kube-dns-rc.yaml' }
  delegate_to: localhost
  ignore_errors: yes

- name: create k8s DNS service and replication controller
  command: "{{item}}"
  with_items:
    - "kubectl apply -f /tmp/kube-dns-rc.yaml"
    - "kubectl apply -f /tmp/kube-dns-svc.yaml"
  delegate_to: localhost
  ignore_errors: yes


- name: generate k8s Dashboard service and deployment files
  template:
    src: "{{item.src}}"
    dest: "/tmp/{{item.dest}}"
    mode: 0644
  with_items:
    - { src: "k8s_dashboard_deployment.yaml.j2", dest: 'kube-dashboard-deploy.yaml' }
    - { src: "k8s_dashboard_service.yaml.j2", dest: 'kube-dashboard-svc.yaml' }
  delegate_to: localhost
  ignore_errors: yes

- name: create k8s Dashboard service and deployment
  command: "{{item}}"
  with_items:
    - "kubectl apply -f /tmp/kube-dashboard-deploy.yaml"
    - "kubectl apply -f /tmp/kube-dashboard-svc.yaml"
  delegate_to: localhost
  ignore_errors: yes
