- name: ensure k8s ssl directory exist
  file:
    path: /etc/kubernetes/ssl
    state: directory
    owner: root
    group: root
    mode: 0700

- name: copy masters ssl certificates
  copy:
    src: "{{item.src}}"
    dest: "/etc/kubernetes/ssl/{{item.dest}}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: "{{k8s_ssl_api_server_path}}/{{k8s_ssl_ca_pem_key_name}}", dest: "{{k8s_ssl_ca_pem_key_name}}" }
    - { src: "{{k8s_ssl_api_server_path}}/{{k8s_ssl_apiserver_pem_name}}", dest: "{{k8s_ssl_apiserver_pem_name}}" }
    - { src: "{{k8s_ssl_api_server_path}}/{{k8s_ssl_apiserver_key_pem_name}}", dest: "{{k8s_ssl_apiserver_key_pem_name}}" }
  when: "'k8s-masters' in group_names"


- name: ensure k8s manifests directory exist
  file:
    path: /etc/kubernetes/manifests
    owner: root
    group: root
    mode: 0755
    state: directory

- name: configure k8s API Server / Proxy / Controller Manager / Scheduler
  template:
    src: "{{item.src}}"
    dest: "/etc/kubernetes/manifests/{{item.dest}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - { src: "k8s_kube_apiserver.yaml.j2", dest: 'kube-apiserver.yaml' }
    - { src: "k8s_kube_proxy_master.yaml.j2", dest: 'kube-proxy.yaml' }
    - { src: "k8s_kube_controller_manager.yaml.j2", dest: 'kube-controller-manager.yaml' }
    - { src: "k8s_kube_scheduler.yaml.j2", dest: 'kube-scheduler.yaml' }
